config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  resources :prospects, only: [ :index, :show, :new, :create, :update, :edit ] do
    resources :comments, only: [ :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prospect
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :status
  has_many :comments, dependent: :destroy
  belongs_to :user

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :prospects, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :prospects
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  #cada vez que quiera cambiar la redireccion, luego de iniciar sesión. Crear el metodo y poner la ruta correspondiente.
  def after_sign_in_path_for(resource)
    prospects_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prospect = Prospect.find(params[:prospect_id])
    @comment = Comment.new(comment_params)
    @user = current_user
    @comment.user = @user
    @comment.prospect = @prospect

    if @comment.save
      redirect_to prospect_path(@prospect)
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
    @prospects = Prospect.all
    @prospect = Prospect.where(status_id: 1).size
    @interested = Prospect.where(status_id: 2).size
    @client = Prospect.where(status_id: 3).size
    @markers = @prospects.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
    end
  end

  def show
    @prospect = Prospect.find(params[:id])
    @comments = @prospect.comments
    @comment = Comment.new
    @marker = [{
      lat: @prospect.latitude,
      lng: @prospect.longitude
    }]
  end

  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new(prospects_params)
    @user = current_user
    @prospect.user_id = @user.id
    if @prospect.save
      redirect_to prospect_path(@prospect)
    else
      render :new
    end
  end

  def edit
    @prospect = Prospect.find(params[:id])
  end

  def update
    @prospect = Prospect.find(params[:id])

    if @prospect.update(prospects_params)
      redirect_to prospect_path(@prospect)
    else
      render :edit
    end
  end

  private
  def prospects_params
    params.require(:prospect).permit(:name, :lastname, :address, :cellphone, :email, :status_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning101</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://kit.fontawesome.com/4722a3e667.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/prospects/_button_back.html.erb
<%= link_to prospects_path, class: "links" do %>
    <i class="fa-solid fa-arrow-left"></i> Regresar atras 
  <% end %>

app/views/prospects/_form.html.erb
  <%= simple_form_for @prospect do |f| %>
  <div class="row">
    <div class="col"> <%= f.input :name %>  </div>
    <div class="col"> <%= f.input :lastname %> </div>
  </div>
  <div class="row">
    <div class="col-8"> <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none"  },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %> </div>
    <div class="col"> <%= f.input :cellphone %> </div>
  </div>
  <div class="row">
    <div class="col"> <%= f.input :email %> </div>
  <div>
    <%= f.input :photo, as: :file %>
    <%= f.association :status, label_method: :status, prompt: 'Elige el status' %>
    <%= f.submit %>
  <% end %>

app/views/prospects/edit.html.erb
<div class="m-5 p-3"> 
  <h2> Edita los datos </h2>
  <%= render "form" %>
</div>

app/views/prospects/index.html.erb
<div class="container-all py-5">
  <div class="pb-4 align-items-center">
    <div class="d-flex justify-content-between my-5">
      <div class=""> 
        <h1 class="title-prospect">Prospectos </h1>
        <div class="box-line"> </div>
        <%= link_to new_prospect_path, class: "links btn btn-nuevo" do %>
        <i class="fa-plus"> Nuevo Prospecto</i>
        <% end %>
      </div>
      <div class="circle-all d-flex justify-content-end""> 
        <div class="circle1"> 
          <div class="circle-number1"> <%= pluralize(@prospect, "Prospecto").first %></div> 
          <p> <%= pluralize(@prospect, "Prospecto")[1..-1] %></p> 
        </div>
        <%# pluralize para el plural %>
        <div class="circle2"> 
          <div class="circle-number2"> <%= pluralize(@interested, "Interesado").first %> </div>
          <div class="circle-word2"> <%= pluralize(@interested, "Interesado")[1..-1] %> </div>
        </div>
        <div class="circle3"> 
          <div class="circle-number3"> <%= pluralize(@client, "Cliente").first %> </div>
          <p> <%= pluralize(@client, "Cliente")[1..-1] %> </p>
        </div>
      </div>
      <%# Circle SE ENCUENTRA EN _table.scss %>
    </div>
  </div>



  <div class="table-list-prospect">
    <table class="">
      <thead>
        <tr>
          <th class="first-column head-table-title" scope="col">Nombres</th>
          <th class="head-table-title" scope="col">Email</th>
          <th class="head-table-title" scope="col">Celular</th>
          <th class="head-table-title" scope="col">Estado</th>
          <th class="head-table-title" scope="col">Fecha de registro</th>
          <th class="head-table-title" scope="col">Ingresado por</th>
          <th class="head-table-title" scope="col">Conversaciones</th>
          <th class="head-table-title" scope="col"></th>

        </tr>
      </thead>

      <tbody class="tbody">
        <% @prospects.each do |prospect| %>
        <tr >
            <td class="first-column">
              <% if prospect.photo.key  %>
                <%= cl_image_tag prospect.photo.key, class: "avatar-img photo-column" %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar-img photo-column" %>
              <% end %>
              <%= prospect.name %>
              <%= prospect.lastname %>
            </td>
            <td> <%= prospect.email %> </td>
            <td> <%= prospect.cellphone %></td>
            <td> <%= prospect.status.status %> </td>
            <td> <%= prospect.created_at.strftime("%Y-%m-%d")%></td>
            <td> <%= prospect.user.email %></td>
            <td> <%= Comment.where(prospect_id: prospect.id).size %></td>

            <td> <%= link_to prospect_path(prospect), class: "links btn btn-border" do %>
            <i class="fa-regular fa-eye"></i>
            <% end %>
            <%= link_to edit_prospect_path(prospect), class: "links btn btn-border" do %>
            <i class="fa-regular fa-pen-to-square"></i>
            <% end %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/prospects/new.html.erb
<div class="mx-5 px-5"> 
<%= render "button_back" %>
  <div class="head-titles-new"> 
    <h2> Crea un nuevo prospecto </h2>
    <p> Rellena los datos correspondientes </p>
  </div>
  <div class="d-flex justify-content-between line">
    <div class="container-description-form"> 

      <div class="content-card-new d-flex align-items-center justify-content-end"> 
        <div class="description-new"> 
          <p class="title-description-new"> Nombre </p> 
          <p class="description-description-new"> Escribe un nombre </p> 
        </div>
        <div class="icon-new"> 
          <i class="fa-solid fa-user"></i>
        </div>
        <div class="circle"> </div>
      </div>

      <div class="content-card-new d-flex align-items-center justify-content-end"> 
        <div class="description-new"> 
          <p class="title-description-new"> Apellido </p> 
          <p class="description-description-new"> Escribe los apellidos </p> 
        </div>
        <div class="icon-new"> 
          <i class="fa-solid fa-user"></i>
        </div>
      <div class="circle"> </div>
      </div>

      <div class="content-card-new d-flex align-items-center justify-content-end"> 
        <div class="description-new"> 
          <p class="title-description-new"> Dirección </p> 
          <p class="description-description-new"> Escribe la Dirección </p> 
        </div>
        <div class="icon-new"> 
          <i class="fa-solid fa-location-crosshairs"></i>
        </div>
      <div class="circle"> </div>
      </div>

      <div class="content-card-new d-flex align-items-center justify-content-end"> 
        <div class="description-new"> 
          <p class="title-description-new"> Email </p> 
          <p class="description-description-new"> Escribe el email </p> 
        </div>
        <div class="icon-new"> 
          <i class="fa-regular fa-envelope"></i>
        </div>
      <div class="circle"> </div>
      </div>
      
    </div>
    

    <div class="line-icon"> </div>
    

    <div class="container-fill-form">
      <div class="fill-titles"> 
        <p> Paso 1/1 </p>
        <h3> ¿Cuál es el nombre? </h3>
        <p> Por favor ingrese el nombre del prospectado </p>
      </div>
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/prospects/show.html.erb
<div class="m-5 p-3">
  <div class="d-flex justify-content-end"> 
    <%= render "button_back" %>

  </div>

  <div class="d-flex">
    <div class="info-prospect">
      <div class="d-flex justify-content-between align-items-start">
        <% if @prospect.photo.key %>
          <%= cl_image_tag @prospect.photo.key, class: "perfil-photo" %>
        <% else %>
          <%= image_tag "avatar.png", class: "perfil-photo" %>
        <% end %>
        <%= link_to edit_prospect_path(@prospect), class: "links btn btn-border" do %>
          <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
      </div>

      <div class="mb-3 d-flex justify-content-between align-items-center">

        <h2> <%= @prospect.name %> <%= @prospect.lastname %></h2>
      </div>

      <p class="info-details"> <i class="fa-solid fa-phone"></i> <%= @prospect.cellphone %> </p>
      <p class="info-details"> <i class="fa-regular fa-envelope"></i> <%= @prospect.email %> </p>
      <p class="info-details"> <i class="fa-solid fa-location-crosshairs"></i> <%= @prospect.address %> </p>

    </div>
    <div class="ms-5" style="width: 100%; height: 400px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @marker.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

  <div class="comments-all">
    <div class="py-3 new-comment">
      <h5> Deja tu comentario </h5>
      <%= simple_form_for [ @prospect, @comment ] do |f| %>
        <div class="form-comment">
           <%= f.input :message, placeholder: "Escribe tu comentario", label: false %>
          <%= f.submit class:"btn btn-comment" %>
        </div>
      <% end %>
    </div>

    <% @comments.each do |comment| %>
      <div class="comments-card d-flex align-items-start">

        <% if comment.user == @prospect.user %>
          <% if comment.user.photo.key %>
            <div class="card-empty d-flex justify-content-center">  <%= cl_image_tag comment.user.photo.key, class: "avatar-img" %> </div>
          <% end %>
          <div class="comments">
            <div class="d-flex justify-content-between align-items-center">
              <p class="comments-user"> <%= comment.user.email %> </p>
              <p class="comments-date"> <%= comment.created_at.strftime("%A %d, %B %Y - %H:%M") %> <%#= I18n.l(comment.created_at, format: '%A, %d de %B de %Y') %> </p>
            </div>
            <p class="comments-comment"> <%= comment.message %> </p>
          </div>
          <div class="card-empty"> </div>
        <% else %>
          <div class="card-empty"> </div>
          <div class="comments">
            <div class="d-flex justify-content-between align-items-center">
              <p class="comments-user"> <%= comment.user.email %> </p>
              <p class="comments-date"> <%= comment.created_at.strftime("%A %d, %B %Y - %H:%M") %> <%#= I18n.l(comment.created_at, format: '%A, %d de %B de %Y') %> </p>
            </div>
            <p class="comments-comment"> <%= comment.message %> </p>
          </div>
          <% if comment.user.photo.key %>
            <div class="card-empty d-flex justify-content-center"> <%= cl_image_tag comment.user.photo.key, class: "avatar-img" %> </div>
          <% end %>
        <% end %>








      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class=" container-all navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo-learning" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <%= javascript_pack_tag 'dropdownPrueba' %>

    <% if user_signed_in? %>

      <%# dropdown desplegado %>
      <div class="dropdown-prueba navbar-nav-prueba hide-options" id="dropdown-prueba">
        <div class="d-flex justify-content-end align-items-center">
          <div class='nav-user'>
            <div class="nav-username"> <%= current_user.name %> </div>
            <div class="nav-email"> <%= current_user.email %> </div>
          </div>
          <%= cl_image_tag current_user.photo.key, class: "avatar" %>
        </div>

        <div class='dropdown-options'>
          <%= link_to "Perfil", "#", class: "links btn btn-dropdown" %>
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "links btn btn-dropdown" %>
        </div>
      </div>

      <%# Dropdown pequeño %>
      <!--
      <div class="dropdown-small hide-options d-none" id="dropdown-small">
        <div class='d-flex align-items-center'>
          <div class="nav-username me-3"> <%= current_user.name %> </div>
          <%= cl_image_tag current_user.photo.key, class: "avatar" %>
        </div>
      </div>
      -->
    <% end %>


  </div>
</div>